In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2],[3,4,5]] 

In [21]:
np.array(my_mat)

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

#### (start,stop,step)

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Evenly spaced values.
(start, stop, no. of values)
Check ex. below

In [29]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

identity matrix

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random values - uniformly distributed between 0 to 1

In [31]:
np.random.rand(5)

array([0.03995383, 0.80392757, 0.32737621, 0.76082875, 0.47844689])

In [32]:
np.random.rand(5,5)

array([[0.35753986, 0.9493537 , 0.45236144, 0.71808922, 0.22948319],
       [0.31852331, 0.94423474, 0.58141059, 0.39229154, 0.62642243],
       [0.94206822, 0.44867208, 0.63675441, 0.91520564, 0.08106262],
       [0.42296369, 0.09543536, 0.6835501 , 0.09726085, 0.86084933],
       [0.00576981, 0.26661354, 0.31929302, 0.95241574, 0.70857022]])

random numbers - from a normal distribution

In [33]:
np.random.randn(2)

array([-1.43853112, -0.92532768])

random integers - includes first arg (ex. 1) excludes second arg (50), third arg - no. of values

In [35]:
np.random.randint(1,50,5)

array([11, 40, 25, 11, 32])

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr = np.random.randint(5,60,10)

In [47]:
ranarr

array([53,  7,  6, 37, 45, 42,  9, 18, 20, 21])

In [48]:
ranarr.max()

53

In [49]:
ranarr.min()

6

ranarr.argmin() returns the index of min value

In [52]:
ranarr.argmin()

2

In [54]:
arr.shape

(25,)

In [60]:
arr1 = arr.reshape(5,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr1.shape

(5, 5)

In [62]:
arr.dtype

dtype('int32')

In [64]:
from numpy.random import randint

In [65]:
randint(2,6)

4

when you import the method then no need to write np.random.randint. As shown above

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr[9]

9

In [68]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [73]:
arr[21:] = 0
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20,  0,  0,  0,  0])

In [75]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [76]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr_2d[2][1]

8

In [78]:
arr_2d[2,1]

8

In [80]:
arr_2d[:2,1:2]

array([[2],
       [5]])

In [84]:
arr = np.arange(11)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
bool_arr = arr > 3

In [90]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [91]:
arr[arr < 5]

array([0, 1, 2, 3, 4])

array with array

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [94]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

array with scalar

In [96]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

universal array functions

In [97]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [98]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [99]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])